spring.datasource.url=jdbc:postgresql://localhost:5432/m9_activity6
spring.datasource.username=cjbgo
spring.datasource.password=YOURPASSWORD

# ✅ Force data.sql to run
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# ✅ Create tables first from JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
